ASCII = {
    " ": [
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       ")
    ],
    "!": [
        list(" __  "),
        list("|  \ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list(" \▓▓ "),
        list(" __  "),
        list("|  \ "),
        list(" \▓▓ "),
        list("     "),
        list("     "),
        list("     ")
    ],
    "#": [
        list("   __  __    "),
        list("  |  \|  \   "),
        list(" _| ▓▓| ▓▓_  "),
        list("|   ▓▓  ▓▓ \ "),
        list(" \▓▓▓▓▓▓▓▓▓▓ "),
        list("|   ▓▓  ▓▓ \ "),
        list(" \▓▓▓▓▓▓▓▓▓▓ "),
        list("  | ▓▓| ▓▓   "),
        list("   \▓▓ \▓▓   "),
        list("             "),
        list("             "),
        list("             ")
    ],
    "%": [
        list(" __    __  "),
        list("|  \  /  \ "),
        list(" \▓▓ /  ▓▓ "),
        list("    /  ▓▓  "),
        list("   /  ▓▓   "),
        list("  /  ▓▓    "),
        list(" /  ▓▓ __  "),
        list("|  ▓▓ |  \ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "'": [
        list(" __  "),
        list("|  \ "),
        list("| ▓▓ "),
        list(" \▓  "),
        list("     "),
        list("     "),
        list("     "),
        list("     "),
        list("     "),
        list("     "),
        list("     "),
        list("     ")
    ],
    "(": [
        list("   ___  "),
        list("  /   \ "),
        list(" /  ▓▓▓ "),
        list("|  ▓▓   "),
        list("| ▓▓    "),
        list("| ▓▓    "),
        list(" \▓▓\_  "),
        list("  \▓▓ \ "),
        list("   \▓▓▓ "),
        list("        "),
        list("        "),
        list("        ")
    ],
    ")": [
        list(" ___    "),
        list("|   \   "),
        list(" \▓▓▓\  "),
        list("   \▓▓\ "),
        list("   | ▓▓ "),
        list("   | ▓▓ "),
        list(" _/  ▓▓ "),
        list("|   ▓▓  "),
        list(" \▓▓▓   "),
        list("        "),
        list("        "),
        list("        ")
    ],
    "+": [
        list("           "),
        list("    __     "),
        list("   |  \    "),
        list(" __| ▓▓__  "),
        list("|    ▓▓  \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("   | ▓▓    "),
        list("    \▓▓    "),
        list("           "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "-": [
        list("         "),
        list("         "),
        list("         "),
        list(" ______  "),
        list("|      \ "),
        list(" \▓▓▓▓▓▓ "),
        list("         "),
        list("         "),
        list("         "),
        list("         "),
        list("         "),
        list("         ")
    ],
    ".": [
        list("     "),
        list("     "),
        list("     "),
        list("     "),
        list("     "),
        list("     "),
        list(" __  "),
        list("|  \ "),
        list(" \▓▓ "),
        list("     "),
        list("     "),
        list("     ")
    ],
    ":": [
        list("     "),
        list("     "),
        list(" __  "),
        list("|  \ "),
        list(" \▓▓ "),
        list("_ _  "),
        list("|  \ "),
        list(" \▓▓ "),
        list("     "),
        list("     "),
        list("     "),
        list("     ")
    ],
    "=": [
        list("       "),
        list("       "),
        list(" ____  "),
        list("|    \ "),
        list(" \▓▓▓▓ "),
        list("|    \ "),
        list(" \▓▓▓▓ "),
        list("       "),
        list("       "),
        list("       "),
        list("       "),
        list("       ")
    ],
    "?": [
        list("  ____   "),
        list(" /    \  "),
        list("|  ▓▓▓▓\ "),
        list(" \▓▓| ▓▓ "),
        list("   /  ▓▓ "),
        list("  |  ▓▓  "),
        list("   \▓▓   "),
        list("  |  \   "),
        list("   \▓▓   "),
        list("         "),
        list("         "),
        list("         ")
    ],
    "@": [
        list("     ______      "),
        list("   _/      \_    "),
        list("  /   ▓▓▓▓▓▓ \   "),
        list(" /  ▓▓▓____▓▓▓\  "),
        list("|  ▓▓/     \ ▓▓\ "),
        list("| ▓▓|  ▓▓▓▓▓| ▓▓ "),
        list("| ▓▓| ▓▓| ▓▓| ▓▓ "),
        list("| ▓▓ \▓▓  ▓▓| ▓▓ "),
        list(" \▓▓\ \▓▓▓▓▓▓▓▓  "),
        list("  \▓▓\ __/   \   "),
        list("   \▓▓▓    ▓▓▓   "),
        list("     \▓▓▓▓▓▓     ")
    ],
    "0": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓▓\| ▓▓ "),
        list("| ▓▓▓▓\ ▓▓ "),
        list("| ▓▓\▓▓\▓▓ "),
        list("| ▓▓_\▓▓▓▓ "),
        list(" \▓▓  \▓▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "1": [
        list("   __    "),
        list(" _/  \   "),
        list("|   ▓▓   "),
        list(" \▓▓▓▓   "),
        list("  | ▓▓   "),
        list("  | ▓▓   "),
        list(" _| ▓▓_  "),
        list("|   ▓▓ \ "),
        list(" \▓▓▓▓▓▓ "),
        list("         "),
        list("         "),
        list("         ")
    ],
    "2": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list(" \▓▓__| ▓▓ "),
        list(" /      ▓▓ "),
        list("|  ▓▓▓▓▓▓  "),
        list("| ▓▓_____  "),
        list("| ▓▓     \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "3": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list(" \▓▓__| ▓▓ "),
        list("  |     ▓▓ "),
        list(" __\▓▓▓▓▓\ "),
        list("|  \__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "4": [
        list(" __    __  "),
        list("|  \  |  \ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__| ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("      | ▓▓ "),
        list("      | ▓▓ "),
        list("       \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "5": [
        list(" _______   "),
        list("|       \  "),
        list("| ▓▓▓▓▓▓▓  "),
        list("| ▓▓____   "),
        list("| ▓▓    \  "),
        list(" \▓▓▓▓▓▓▓\ "),
        list("|  \__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "6": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓___\▓▓ "),
        list("| ▓▓    \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "7": [
        list(" ________  "),
        list("|        \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("    /  ▓▓  "),
        list("   /  ▓▓   "),
        list("  /  ▓▓    "),
        list(" /  ▓▓     "),
        list("|  ▓▓      "),
        list(" \▓▓       "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "8": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓__/ ▓▓ "),
        list(" >▓▓    ▓▓ "),
        list("|  ▓▓▓▓▓▓  "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "9": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list(" _\▓▓▓▓▓▓▓ "),
        list("|  \__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "a": [
        list("           "),
        list("           "),
        list("  ______   "),
        list(" |      \  "),
        list("  \▓▓▓▓▓▓\ "),
        list(" /      ▓▓ "),
        list("|  ▓▓▓▓▓▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "b": [
        list(" __        "),
        list("|  \       "),
        list("| ▓▓____   "),
        list("| ▓▓    \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list(" \▓▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "c": [
        list("           "),
        list("           "),
        list("  _______  "),
        list(" /       \ "),
        list("|  ▓▓▓▓▓▓▓ "),
        list("| ▓▓       "),
        list("| ▓▓_____  "),
        list(" \▓▓     \ "),
        list("  \▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "d": [
        list("       __  "),
        list("      |  \ "),
        list("  ____| ▓▓ "),
        list(" /      ▓▓ "),
        list("|  ▓▓▓▓▓▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "e": [
        list("           "),
        list("           "),
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓    ▓▓ "),
        list("| ▓▓▓▓▓▓▓▓ "),
        list(" \▓▓     \ "),
        list("  \▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "f": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓_  \▓▓ "),
        list("| ▓▓ \     "),
        list("| ▓▓▓▓     "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list(" \▓▓       "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "g": [
        list("           "),
        list("           "),
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list(" _\▓▓▓▓▓▓▓ "),
        list("|  \__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  ")
    ],
    "h": [
        list(" __        "),
        list("|  \       "),
        list("| ▓▓____   "),
        list("| ▓▓    \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "i": [
        list(" __  "),
        list("|  \ "),
        list(" \▓▓ "),
        list("|  \ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list(" \▓▓ "),
        list("     "),
        list("     "),
        list("     ")
    ],
    "j": [
        list("           "),
        list("           "),
        list("       __  "),
        list("      |  \ "),
        list("       \▓▓ "),
        list("      |  \ "),
        list("      | ▓▓ "),
        list("      | ▓▓ "),
        list(" __   | ▓▓ "),
        list("|  \__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  ")
    ],
    "k": [
        list(" __        "),
        list("|  \       "),
        list("| ▓▓   __  "),
        list("| ▓▓  /  \ "),
        list("| ▓▓_/  ▓▓ "),
        list("| ▓▓   ▓▓  "),
        list("| ▓▓▓▓▓▓\  "),
        list("| ▓▓  \▓▓\ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "l": [
        list(" __  "),
        list("|  \ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list("| ▓▓ "),
        list(" \▓▓ "),
        list("     "),
        list("     "),
        list("     ")
    ],
    "m": [
        list("               "),
        list("               "),
        list(" ______ ____   "),
        list("|      \    \  "),
        list("| ▓▓▓▓▓▓\▓▓▓▓\ "),
        list("| ▓▓ | ▓▓ | ▓▓ "),
        list("| ▓▓ | ▓▓ | ▓▓ "),
        list("| ▓▓ | ▓▓ | ▓▓ "),
        list(" \▓▓  \▓▓  \▓▓ "),
        list("               "),
        list("               "),
        list("               ")
    ],
    "n": [
        list("           "),
        list("           "),
        list(" _______   "),
        list("|       \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "o": [
        list("           "),
        list("           "),
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "p": [
        list("           "),
        list("           "),
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list("| ▓▓▓▓▓▓▓  "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list(" \▓▓       ")
    ],
    "q": [
        list("           "),
        list("           "),
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓▓ "),
        list("      | ▓▓ "),
        list("      | ▓▓ "),
        list("       \▓▓ ")
    ],
    "r": [
        list("           "),
        list("           "),
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓   \▓▓ "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list(" \▓▓       "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "s": [
        list("           "),
        list("           "),
        list("  _______  "),
        list(" /       \ "),
        list("|  ▓▓▓▓▓▓▓ "),
        list(" \▓▓    \  "),
        list(" _\▓▓▓▓▓▓\ "),
        list("|       ▓▓ "),
        list(" \▓▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "t": [
        list("   __      "),
        list("  |  \     "),
        list(" _| ▓▓_    "),
        list("|   ▓▓ \   "),
        list(" \▓▓▓▓▓▓   "),
        list("  | ▓▓ __  "),
        list("  | ▓▓|  \ "),
        list("   \▓▓  ▓▓ "),
        list("    \▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "u": [
        list("           "),
        list("           "),
        list(" __    __  "),
        list("|  \  |  \ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "v": [
        list("            "),
        list("            "),
        list(" __     __  "),
        list("|  \   /  \ "),
        list(" \▓▓\ /  ▓▓ "),
        list("  \▓▓\  ▓▓  "),
        list("   \▓▓ ▓▓   "),
        list("    \▓▓▓    "),
        list("     \▓     "),
        list("            "),
        list("            "),
        list("            ")
    ],
    "w": [
        list("               "),
        list("               "),
        list(" __   __   __  "),
        list("|  \ |  \ |  \ "),
        list("| ▓▓ | ▓▓ | ▓▓ "),
        list("| ▓▓ | ▓▓ | ▓▓ "),
        list("| ▓▓_/ ▓▓_/ ▓▓ "),
        list(" \▓▓   ▓▓   ▓▓ "),
        list("  \▓▓▓▓▓\▓▓▓▓  "),
        list("               "),
        list("               "),
        list("               ")
    ],
    "x": [
        list("           "),
        list("           "),
        list(" __    __  "),
        list("|  \  /  \ "),
        list(" \▓▓\/  ▓▓ "),
        list("  >▓▓  ▓▓  "),
        list(" /  ▓▓▓▓\  "),
        list("|  ▓▓ \▓▓\ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "y": [
        list("           "),
        list("           "),
        list(" __    __  "),
        list("|  \  |  \ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list(" _\▓▓▓▓▓▓▓ "),
        list("|  \__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  ")
    ],
    "z": [
        list("           "),
        list("           "),
        list(" ________  "),
        list("|        \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("  /    ▓▓  "),
        list(" /  ▓▓▓▓_  "),
        list("|  ▓▓    \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "A": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓__| ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list("| ▓▓▓▓▓▓▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "B": [
        list(" _______   "),
        list("|       \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓__/ ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓__/ ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list(" \▓▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "C": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓   \▓▓ "),
        list("| ▓▓       "),
        list("| ▓▓   __  "),
        list("| ▓▓__/  \ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "D": [
        list(" _______   "),
        list("|       \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list(" \▓▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "E": [
        list(" ________  "),
        list("|        \ "),
        list("| ▓▓▓▓▓▓▓▓ "),
        list("| ▓▓__     "),
        list("| ▓▓  \    "),
        list("| ▓▓▓▓▓    "),
        list("| ▓▓_____  "),
        list("| ▓▓     \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "F": [
        list(" ________  "),
        list("|        \ "),
        list("| ▓▓▓▓▓▓▓▓ "),
        list("| ▓▓__     "),
        list("| ▓▓  \    "),
        list("| ▓▓▓▓▓    "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list(" \▓▓       "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "G": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓ __\▓▓ "),
        list("| ▓▓|    \ "),
        list("| ▓▓ \▓▓▓▓ "),
        list("| ▓▓__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "H": [
        list(" __    __  "),
        list("|  \  |  \ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__| ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list("| ▓▓▓▓▓▓▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "I": [
        list(" ______  "),
        list("|      \ "),
        list(" \▓▓▓▓▓▓ "),
        list("  | ▓▓   "),
        list("  | ▓▓   "),
        list("  | ▓▓   "),
        list(" _| ▓▓_  "),
        list("|   ▓▓ \ "),
        list(" \▓▓▓▓▓▓ "),
        list("         "),
        list("         "),
        list("         ")
    ],
    "J": [
        list("    _____  "),
        list("   |     \ "),
        list("    \▓▓▓▓▓ "),
        list("      | ▓▓ "),
        list(" __   | ▓▓ "),
        list("|  \  | ▓▓ "),
        list("| ▓▓__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "K": [
        list(" __    __  "),
        list("|  \  /  \ "),
        list("| ▓▓ /  ▓▓ "),
        list("| ▓▓/  ▓▓  "),
        list("| ▓▓  ▓▓   "),
        list("| ▓▓▓▓▓\   "),
        list("| ▓▓ \▓▓\  "),
        list("| ▓▓  \▓▓\ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "L": [
        list(" __        "),
        list("|  \       "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list("| ▓▓_____  "),
        list("| ▓▓     \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "M": [
        list(" __       __  "),
        list("|  \     /  \ "),
        list("| ▓▓\   /  ▓▓ "),
        list("| ▓▓▓\ /  ▓▓▓ "),
        list("| ▓▓▓▓\  ▓▓▓▓ "),
        list("| ▓▓\▓▓ ▓▓ ▓▓ "),
        list("| ▓▓ \▓▓▓| ▓▓ "),
        list("| ▓▓  \▓ | ▓▓ "),
        list(" \▓▓      \▓▓ "),
        list("              "),
        list("              "),
        list("              ")
    ],
    "N": [
        list(" __    __  "),
        list("|  \  |  \ "),
        list("| ▓▓\ | ▓▓ "),
        list("| ▓▓▓\| ▓▓ "),
        list("| ▓▓▓▓\ ▓▓ "),
        list("| ▓▓\▓▓ ▓▓ "),
        list("| ▓▓ \▓▓▓▓ "),
        list("| ▓▓  \▓▓▓ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "O": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "P": [
        list(" _______   "),
        list("|       \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓__/ ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list("| ▓▓▓▓▓▓▓  "),
        list("| ▓▓       "),
        list("| ▓▓       "),
        list(" \▓▓       "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "Q": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓ _| ▓▓ "),
        list("| ▓▓/ \ ▓▓ "),
        list(" \▓▓ ▓▓ ▓▓ "),
        list("  \▓▓▓▓▓▓\ "),
        list("      \▓▓▓ "),
        list("           "),
        list("           ")
    ],
    "R": [
        list(" _______   "),
        list("|       \  "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓__| ▓▓ "),
        list("| ▓▓    ▓▓ "),
        list("| ▓▓▓▓▓▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "S": [
        list("  ______   "),
        list(" /      \  "),
        list("|  ▓▓▓▓▓▓\ "),
        list("| ▓▓___\▓▓ "),
        list(" \▓▓    \  "),
        list(" _\▓▓▓▓▓▓\ "),
        list("|  \__| ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "T": [
        list(" ________  "),
        list("|        \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("   | ▓▓    "),
        list("   | ▓▓    "),
        list("   | ▓▓    "),
        list("   | ▓▓    "),
        list("   | ▓▓    "),
        list("    \▓▓    "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "U": [
        list(" __    __  "),
        list("|  \  |  \ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓  | ▓▓ "),
        list("| ▓▓__/ ▓▓ "),
        list(" \▓▓    ▓▓ "),
        list("  \▓▓▓▓▓▓  "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "V": [
        list(" __     __  "),
        list("|  \   |  \ "),
        list("| ▓▓   | ▓▓ "),
        list("| ▓▓   | ▓▓ "),
        list(" \▓▓\ /  ▓▓ "),
        list("  \▓▓\  ▓▓  "),
        list("   \▓▓ ▓▓   "),
        list("    \▓▓▓    "),
        list("     \▓     "),
        list("            "),
        list("            "),
        list("            ")
    ],
    "W": [
        list(" __       __  "),
        list("|  \  _  |  \ "),
        list("| ▓▓ / \ | ▓▓ "),
        list("| ▓▓/  ▓\| ▓▓ "),
        list("| ▓▓  ▓▓▓\ ▓▓ "),
        list("| ▓▓ ▓▓\▓▓\▓▓ "),
        list("| ▓▓▓▓  \▓▓▓▓ "),
        list("| ▓▓▓    \▓▓▓ "),
        list(" \▓▓      \▓▓ "),
        list("              "),
        list("              "),
        list("              ")
    ],
    "X": [
        list(" __    __  "),
        list("|  \  |  \ "),
        list("| ▓▓  | ▓▓ "),
        list(" \▓▓\/  ▓▓ "),
        list("  >▓▓  ▓▓  "),
        list(" /  ▓▓▓▓\  "),
        list("|  ▓▓ \▓▓\ "),
        list("| ▓▓  | ▓▓ "),
        list(" \▓▓   \▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ],
    "Y": [
        list(" __      __  "),
        list("|  \    /  \ "),
        list(" \▓▓\  /  ▓▓ "),
        list("  \▓▓\/  ▓▓  "),
        list("   \▓▓  ▓▓   "),
        list("    \▓▓▓▓    "),
        list("    | ▓▓     "),
        list("    | ▓▓     "),
        list("     \▓▓     "),
        list("             "),
        list("             "),
        list("             ")
    ],
    "Z": [
        list(" ________  "),
        list("|        \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("    /  ▓▓  "),
        list("   /  ▓▓   "),
        list("  /  ▓▓    "),
        list(" /  ▓▓___  "),
        list("|  ▓▓    \ "),
        list(" \▓▓▓▓▓▓▓▓ "),
        list("           "),
        list("           "),
        list("           ")
    ]
}
